if has('vim_starting')
    set nocompatible
    filetype off
    set runtimepath+=~/.vim/bundle/neobundle.vim
endif 

call neobundle#rc(expand('~/.vim/bundle'))

NeoBundleFetch 'Shougo/neobundle.vim'

NeoBundle 'scrooloose/nerdtree'
NeoBundle 'scrooloose/nerdcommenter'
NeoBundle 'wombat256.vim'
NeoBundle 'godlygeek/tabular'
NeoBundle 'bling/vim-airline'
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'Shougo/vimshell.vim', {'build': {'unix': 'make'}}
NeoBundle 'Shougo/vimproc.vim', {'build': {'unix': 'make'}}
NeoBundle 'Shougo/unite.vim'


syntax on
let mapleader=","   " the leader command should be a comma rather than a slash
set tabstop=4       " tabstop every 4 'spaces'
set shiftwidth=4    " shiftwidth the same as a single tabstop
set softtabstop=4
set expandtab       " tab to spaces
set visualbell      " prevent beeps
set laststatus=2    " always show modeline
set textwidth=0
set linebreak       " linebreak at words
set nowrap          " default is not to wrap

" Airline modifications
set ttimeoutlen=50
let g:airline_detect_whitespace=0
let g:airline_theme='badwolf'

" simplified split navigation
" <C-w> v - vertical split
" <C-w> s - horizontal split
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" reformat paragraph
map <leader>p gwap

" reload configuration
map <leader>v :sp $MYVIMRC<CR>
map <leader>V :source $MYVIMRC<CR>

" reduce noise browsing for files
set wildignore=*.pyc,*.o,*.so,*.os

" Unite keybindings
nnoremap <C-p> :Unite file_rec/async<cr>

" colorscheme
try
    set t_Co=256
    colorscheme wombat256mod
catch
endtry

" spelling
set spelllang=en_au
set spellfile=$HOME/.vimspell.add
syntax spell toplevel

" nerdtree
autocmd VimEnter * if exists(":NERDTree") | exe "nnoremap <leader>n :NERDTreeToggle\<CR>" | endif

" Filetype remappings
autocmd BufRead,BufNewFile,BufFilePost *.md set filetype=markdown
autocmd BufRead,BufNewFile,BufFilePost */SConscript set filetype=python
autocmd BufRead,BufNewFile,BufFilePost */SConstruct set filetype=python

" For editing prose documents, enable spelling
autocmd FileType tex,rst,md setlocal spell

" For makefiles, we want to use tabs, not spaces
autocmd FileType make set noexpandtab

filetype plugin indent on

NeoBundleCheck
