" :PlugInstall to add plugins
call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/syntastic'
Plug 'wombat256.vim'
Plug 'godlygeek/tabular'
Plug 'bling/vim-airline'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'kien/ctrlp.vim'
call plug#end()

syntax on

let mapleader=","   " the leader command should be a comma rather than a slash
set nocompatible
set tabstop=4       " tabstop every 4 'spaces'
set shiftwidth=4    " shiftwidth the same as a single tabstop
set softtabstop=4
set expandtab       " tab to spaces
set visualbell      " prevent beeps
set laststatus=2    " always show modeline
set textwidth=0
set linebreak       " linebreak at words
set nowrap          " default is not to wrap
set wildignore=*.pyc,*.o,*.so,*.os " reduce noise browsing for files
set spelllang=en_au
set spellfile=$HOME/.vimspell.add
set t_Co=256
syntax spell toplevel

try
    colorscheme wombat256mod
catch
endtry

" Split navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" reload configuration
map <leader>v :sp $MYVIMRC<CR>

" Filetype remappings
" These could be in ftdetect, but ok here for now
au BufRead,BufNewFile,BufFilePost *.md set filetype=markdown
au BufRead,BufNewFile,BufFilePost */SConscript set filetype=python
au BufRead,BufNewFile,BufFilePost */SConstruct set filetype=python

" Airline modifications
set ttimeoutlen=50
"let g:airline_detect_whitespace=0
let g:airline_theme='badwolf'
let g:airline#extensions#syntastic#enabled = 1

map <silent> <Leader>e :Errors<CR>
map <Leader>s :SyntasticToggleMode<CR>

