#!/bin/bash

PATH=$PATH:~/.local/bin

function installpip {
    # check if pip is available (even if it's system pip)
    which pip > /dev/null
    if [[ "$?" != "0" ]]; then
        wget -c https://raw.github.com/pypa/pip/master/contrib/get-pip.py
        python get-pip.py --user
        pip install --upgrade pip wheel virtualenvwrapper --user
    fi
}

pip wheel -r python/requirements.txt
pip install -r python/requirements.txt --user



